### DISCUSSION TITLE
No files were found with provided sources.

### DISCUSSION THREAD

**Discussion by MrHinsh** [qetza/replacetokens-task#42] [General]
I must be crazy but its not working for me...

![image](https://github.com/qetza/replacetokens-task/assets/5205575/b527480b-df1b-4628-9076-900f7d4cc53b)

All I get is "No files were found with provided sources." when I dump the folder structure, I get all of the correct files...

```
- stage: DocsBuildStage
  displayName: 'Docs Build Stage'
  dependsOn: 
   - SetupStage
  condition:  and(succeeded(), or(eq(dependencies.SetupStage.outputs['ConfigJob.VersionOut.runRelease'], true), eq(variables['buildDocs'], true)))
  jobs:
  - job: JekyllBuildJob
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      environmentName: $[ stageDependencies.SetupStage.ConfigJob.outputs['VersionOut.environmentName'] ]
      releaseTag: $[ stageDependencies.SetupStage.ConfigJob.outputs['VersionOut.releaseTag'] ]
      runRelease: $[ stageDependencies.SetupStage.ConfigJob.outputs['VersionOut.runRelease'] ]
      GitVersion.SemVer: $[ stageDependencies.SetupStage.ConfigJob.outputs['GitVersion.SemVer'] ]
      GitVersion.PreReleaseTag: $[ stageDependencies.SetupStage.ConfigJob.outputs['GitVersion.PreReleaseTag'] ]
    steps:
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '>= 3.0.7'
        addToPath: true
    - task: PowerShell@2
      displayName: Folders
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)"
          Write-Host "ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)"
          Get-ChildItem -Path .\ -Recurse -Directory | Select-Object FullName
          
    - task: replacetokens@6
      inputs:
        sources: '**\*.md;**\*.html'
        addBOM: true
```

See https://dev.azure.com/nkdagility/AzureDevOps-Tools/_build/results?buildId=4917&view=logs&j=7253a11e-eaad-567d-1ec1-798b294cd03b&t=215247fa-994d-5278-de03-47b674464e38

**Comment by qetza** [comment]
Hi @MrHinsh,
There's a breaking change in v6 due to using `fast-glob`: your paths must use forward slashes `/` as directory separator.

```yaml
- task: replacetokens@6
  inputs:
    sources: '**/*.md;**/*.html'
    addBOM: true
```
