### ISSUE TITLE
v6 not injecting tokens where pattern is enclosed in double quotes

### ISSUE THREAD

**Issue by rebeccajenkinsquest** [qetza/replacetokens-task#23]
Issue encountered after upgrading pipelines to use v6. Here is an example of the inputs we updated to, which were tested successfully against variables indicated simply with -- but not when surrounded by double quotes--e.g., "--VARIABLE--".

```
                tokenPattern: custom
                tokenPrefix: '--'
                tokenSuffix: '--'
```

Is this behavior unexpected, or is there a recommendation for how this can be configured differently from our side?

**Comment by qetza** [comment]
Hi @rebeccajenkinsquest,
I've tried to reproduce your issue but didn't have any error.

My test pipeline:
```yaml
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  VARIABLE: value

steps:
  - task: replacetokens@6
    inputs:
      root: 'issue-23'
      sources: '*.json'
      tokenPattern: 'custom'
      tokenPrefix: '--'
      tokenSuffix: '--'
      logLevel: 'debug'
```

My test file `issue-23/data.json`
```json
{
  "var": "--VARIABLE--"
}
```

output
![image](https://github.com/qetza/replacetokens-task/assets/8191369/618e3131-703d-4f50-844a-6d5abdff8340)

Could you share with me some more details? Your redacted debug logs?
