### ISSUE TITLE
transforms: true does not work

### ISSUE THREAD

**Issue by twinpiloot** [qetza/replacetokens-task#25]
The release notes say that enableTransforms has been renamed to transforms. This does not seem to be true. transforms does not work while enableTransforms still work.

**Comment by qetza** [comment]
Hi @twinpiloot,
Could you provide some logs as i have no issue using `transforms` in the new version 6 of the task; i also kept `enableTransforms` as alias in v6 to simplify upgrade.

For previous versions the input name hasn't changed.

**Comment by qetza** [comment]
That's strange, could you share your the task configuration so that i can try to reproduce?

**Comment by twinpiloot** [comment]
This is what I had. Could it be that you are using version 6.0.5 and I 6.0.4?

- task: replacetokens@6
  displayName: 'Tokenize Configuration files and PowerShell scripts'
  inputs:
    root: '$(Pipeline.Workspace)'
    sources: |
      **/*.ps1
      **/*.json
    encoding: 'auto'
    addBOM: true
    escape: 'off'
    missingVarLog: 'error'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    transforms: true

**Comment by qetza** [comment]
The changes between 6.0.4 and 6.0.5 didn't change anything on inputs or transforms.

I've tested with this YAML and still it's working:
```yaml
- task: replacetokens@6
  inputs:
    root: '$(Pipeline.Workspace)'
    sources: |
      **/issue-25/*.txt
    encoding: 'auto'
    addBOM: true
    escape: 'off'
    missingVarLog: error
    keepToken: false
    tokenPrefix: '#{'
    tokenSufix: '#{'
    transforms: true
    logLevel: debug
```

I though maybe it was the agent not understanding input aliases but you are using other aliases (root, sources, addBOM...) without issues.

Could you share a **redacted** log with system diagnostics enabled to see what are the inputs received by the task?

Also not that you should replace `keepToken: false` with `missingVarAction: none`
