### ISSUE TITLE
utf-16le files are corrupt after token replace (V6)

### ISSUE THREAD

**Issue by petertheautomator** [qetza/replacetokens-task#27]
We upgraded replacetokens from V4 to V6 and all UTF-16le files that are processed become corrupted.

**How to replicate**
- Create a Windows scheduled task and export it to xml (this xml is utf-16le by default)
- replace for the example the description with #{description}#
- run the replacetokens@v6 task
- try to import the xml in Windows scheduled task.

error in the example:
![image](https://github.com/qetza/replacetokens-task/assets/75072402/0e15d2d8-0895-453f-b985-d69c27442867)

**Settings:**
```
- task: replacetokens@6
    displayName: "Replace tokens"
    inputs:
      sources: filles/task.xml
      missingVarLog: 'error'
      transforms: true
      telemetryOptout: true
```

**Comment by qetza** [comment]
Hi @petertheautomator,
One breaking change in v6 is that the default value from _addBom_ (previously _writeBOM_) is now `false` instead of `true` which is causing your issue.

With the following settings it will work:
```yaml
- task: replacetokens@6
    displayName: "Replace tokens"
    inputs:
      sources: filles/task.xml
      addBOM: true
      missingVarLog: 'error'
      transforms: true
      telemetryOptout: true
```
