### ISSUE TITLE
[Question] Any escape options?

### ISSUE THREAD

**Issue by kirill-d-lappo** [qetza/replacetokens-task#28]
Does the task support escaping?

In my case I have kubernetes manifest  file, where I replace values in labels.

But I have problems when value of a variable contains double quotes.

For example:

```yaml
label: "${LABEL_VALUE}"
```

with 

```
LABEL_VALUE='text with "quoted" word'
```

will result in invalid yaml file.

---

task version: 5

**Comment by qetza** [comment]
Hi @kirill-d-lappo,
Yes it's possible to define custom escaping.

The following inputs will escape backslashes `\` and double quotes `"` with a backslash `\`:
```yaml
- task: replacetokens@5
  inputs:
    targetFiles: manifest.yml
    escapeType: custom
    escapeChar: '\'
    charsToEscape: '\"'
    tokenPattern: custom
    tokenPrefix: '${'
    tokenSuffix: '}'
```

Due to how the custom escaping is done it's important to set the escape character as the first character in `charsToEscape`.
