### ISSUE TITLE
possibly update documentation for v6 breaking changes: tokenPattern = custom

### ISSUE THREAD

**Issue by pietersap** [qetza/replacetokens-task#35]
We've upgraded from v3 to v6. In the v3, we used a custom tokenPrefix and tokenSuffix, but we did not set a value for tokenPattern.

In the v6, this turned out to be broken. Here, we also need to add "tokenPattern: custom" to make it work again. This could be clarified in the list of breaking changes for v6 that I found [here ](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens). The list of breaking changes is otherwise very clear, thank you.

Code before upgrade:
```
  - task: replacetokens@3
    displayName: 'Replace tokens'
    inputs:
      rootDirectory: ${{ parameters.rootDirectory }}
      targetFiles: ${{ parameters.targetFiles }}
      escapeType: none
      enableTransforms: true 
      actionOnMissing: fail
      tokenPrefix: ##{{
      tokenSuffix: }}##
```

Code after upgrade (broken)
```
  - task: replacetokens@6
    displayName: 'Replace tokens'
    inputs:
      root: ${{ parameters.rootDirectory }}
      sources: ${{ parameters.targetFiles }}
      escape: off
      transforms: true 
      missingVarLog: error
      tokenPrefix: ##{{
      tokenSuffix: }}##
```

Code after upgrade (fixed again)
```
  - task: replacetokens@6
    displayName: 'Replace tokens'
    inputs:
      root: ${{ parameters.rootDirectory }}
      sources: ${{ parameters.targetFiles }}
      escape: off
      transforms: true 
      missingVarLog: error
      tokenPattern: custom
      tokenPrefix: ##{{
      tokenSuffix: }}##
```
