### ISSUE TITLE
Replacetoken3 to 6 not working for me

### ISSUE THREAD

**Issue by GSMR369** [qetza/replacetokens-task#39]
Below conversion from task@3 to task@6 is not working. 0 token out of 0. Can you pls explain the problem here.

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
inputs:
rootDirectory:"$(System.DefaultWorkingDirectory)/config/"
targetFiles: "configuration.properties.template => configuration.properties
encoding: "auto"
writeBOM: true
actionOnMissing: "warn
keepToken: false
tokenPrefix:{{
tokenSuffix:}}
useLegacyPattern: false
enableTelemetry: true

- task: qetza.replacetokens.replacetokens-task.replacetokens@6
inputs:
root: "$(System.DefaultWorkingDirectory)/config/"
sources: "configuration.properties.template => configuration.properties"
encoding: "auto"
addBOM: true
missingVarLog: "warn"
keep: false
tokenPrefix:{{
tokenSuffix:}}
#useLegacyPattern: false
enableTelemetry: true

**Comment by qetza** [comment]
Hi @GSMR369,
Based on your v3 configuration here is the corresponding v6:

```yaml
- task: replacetokens@6
  inputs:
    root: "$(System.DefaultWorkingDirectory)/config/"
    sources: "configuration.properties.template => configuration.properties"
    encoding: auto
    addBOM: true
    missingVarAction: none
    missingVarLog: warn
    tokenPattern: doublebraces
    telemetryOptout: false
```

If you want to simplify as you are using default values you can use:

```yaml
- task: replacetokens@6
  inputs:
    root: "$(System.DefaultWorkingDirectory)/config/"
    sources: "configuration.properties.template => configuration.properties"
    addBOM: true
    tokenPattern: doublebraces
```
