### ISSUE TITLE
Support for task variables

### ISSUE THREAD

**Issue by ThibaultLesuisse** [qetza/replacetokens-task#46]
My use case is pretty straight forward (I think). I generate an image version dynamically and export it as a task variable. 
``` yaml
- powershell:  ##vso[task.setvariable variable=image_version]$ImageVersion
- task: replacetokens@6
  inputs:
    sources: 'values.pkrvars.hcl'
    additionalVariables: 'image_version: $(image_version)'
    logLevel: 'debug'
```

Is something like this possible? Or am I not reading the docs right?
