### ISSUE TITLE
Replace Tokens - 'init' not found - name not supplied

### ISSUE THREAD

**Issue by phil1234567891011** [qetza/replacetokens-task#58]
I need to replace a particular file tokens, so I have set the sources to

`src/some_folder/somes_cript.py`

As the pipeline is launched, the template is called and ran properly

but I get these errors:

```
token pattern '__\s*((?:(?!__)(?!\s*__).)*)\s*__'
transform pattern '\s*(.*)\(\s*((?:(?!\()(?!\s*\)).)*)\s*\)\s*'
 replacing tokens in '/home/someuser/agent/_work/8/s/src/some_folder/some_script.py'
encoding 'ascii'
##[error]variable 'init' not found
init: 
##[error]Error: name not supplied
```

"init" is nowhere to be found in the project (appart from _ _ init _ _ constructors in .py files)

This is my pipeline template :

```
parameters:
  - name: targetDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)'

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@6
    name: replace_tokens
    displayName: "Inject secrets"
    inputs:
      root: "${{ parameters.targetDirectory }}"
      sources: |
        **/src/some_folder/some_script.py
      tokenPattern: 'doubleunderscores'
      logLevel: 'debug'
      missingVarLog: 'error'
```

Thanks for your help
