### ISSUE TITLE
Possibility to limit replacement variables to those explicitely provided

### ISSUE THREAD

**Issue by dmytro-arkhypenko** [qetza/replacetokens-task#60]
I have a concern that exposing all pipeline variables for replacement might give out sensitive information if replaced happened in the manifest files placed by ill-intended party.

I can't come with exact scenario of successful attack exploiting this feature, but having more control over the task behavoir would give me more confidence.

The feature I want might be implmented by introducing additional input `usePipelineVariables`, being `true` by default.

```
- task: qetza.replacetokens.replacetokens-task.replacetokens@6
  inputs:
    sources: '**/*.json'
    usePipelineVariables: 'false'     # 'true by default'
    additionalVariables: |
      - '@**/vars.(json|yml|yaml)'      # read from files
      - '$ENV_VARS',                         # read from env
      - var1: '${{ parameters.var1 }}'  # inline key/value pairs
        var2: '${{ parameters.var2 }}'
```
