### ISSUE TITLE
Unexpected value 'telemetryOptout'

### ISSUE THREAD

**Issue by richardherbert** [qetza/replacetokens-task#71]
I'm getting the error `Unexpected value 'telemetryOptout'` in the following snippet:

```
- task: qetza.replacetokens.replacetokens-task.replacetokens@6
  displayName: 'Replace placeholders in .env'
  telemetryOptout: true
  inputs:
    sources: "${{ parameters.siteDeployLocation }}/.env"
    additionalVariables: |
      - SSO_PUBLIC_KEY: $(${{ parameters.environment }}-SSO_PUBLIC_KEY)
```

**Comment by qetza** [comment]
Hi @richardherbert,
Sorry for the late reply, the `telemetryOptout` is an input parameter:
```yaml
- task: qetza.replacetokens.replacetokens-task.replacetokens@6
  displayName: 'Replace placeholders in .env'
  inputs:
    telemetryOptout: true
    sources: "${{ parameters.siteDeployLocation }}/.env"
    additionalVariables: |
      - SSO_PUBLIC_KEY: $(${{ parameters.environment }}-SSO_PUBLIC_KEY)
```
