### ISSUE TITLE
Replace lower case variables

### ISSUE THREAD

**Issue by nulllogicone** [qetza/replacetokens-task#78]
The tool seems to work great, I have a folder hierarchy full of yml files with variables, and many json files where I want to replace them. It works. My problem is that the variables in json look like ##someVariableName## and those can't be found and replaced with empty string.
I enabled detail logs and have seen that all variables were loaded in uppercase and with prefix named VARIABLES. When I change to ##VARIABLES.SOMEVARIABLENAME## then it works.

My variables yml files look like

```yml
variables:   
  subscriptionId: ‘9932bdda-1649-42a3-a7b0-7fa2a500f535’
```
My json files where I want to replace them looks like
```json
{
    "subscription": {
      "value": "##subscriptionId##"
    }
}
```
The task definition in azure-pipeline.yml
```yml
- task: [qetza.replacetokens.replacetokens-task.replacetokens@6](mailto:qetza.replacetokens.replacetokens-task.replacetokens@6)
      inputs:
        sources: 'pipeline/infra/parameters/**/*.json' 
        additionalVariables: '@globalVariables/**/*.yml' 
        tokenPattern: 'custom'
        tokenPrefix: '##'
        tokenSuffix: '##'
        logLevel: 'info'
        missingVarAction: 'keep'
        missingVarLog: 'error'
```
